name: Update Changelog  

on:  
  schedule:  
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:  # manual

jobs:  
  update-changelog:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2  

      - name: Get changes from upstream  
        run: |  
          # Clone the other user's repository  
          git clone https://github.com/PanoSeiza/FancyMenuTest.git /tmp/repo  
          # Go to the directory  
          cd /tmp/repo  
          # Fetch the latest changes  
          git pull origin master  
          
      - name: Compare changelogs  
        run: |  
          # Sort both changelog files before comparing  
          sort ./changelog.txt -o ./changelog.txt  
          sort /tmp/repo/changelog.txt -o /tmp/repo/changelog.txt  

          # Compare existing changelog.txt with the upstream changelog.txt using comm  
          echo "Finding differences..."  
          if ! comm -13 <(sort ./changelog.txt) <(sort /tmp/repo/changelog.txt) > changelog_diff.txt; then  
            echo "Differences found. Saving to changelog_diff.txt."  
            # Append the new content from changelog.txt to changelog.txt  
            new_entries=$(comm -13 <(sort ./changelog.txt) <(sort /tmp/repo/changelog.txt))  
            echo "$new_entries" >> ./changelog.txt  
          else  
            echo "No differences found."  
            # Remove changelog_diff.txt if it was created without differences  
            rm changelog_diff.txt  
          fi  

      - name: Commit and push changes  
        run: |  
          if [ -f changelog_diff.txt ]; then  
            git config --local user.email "justrandom.work@gmail.com"  
            git config --local user.name "Seiza"  
            git add changelog.txt changelog_diff.txt  
            git commit -m "Update changelog.txt and changelog_diff.txt with differences from upstream changelog.txt"  
            git push origin main  # Change 'main' if your default branch is different  
          else  
            echo "No changes to commit."  
          fi  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
